# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "About"
  pageRef = "whoami"
  weight = 10

[[main]]
  name = "Offensive Security"
  pageRef = "offensiveSecurity"
  weight = 25
  [[main]]
    name = "Web Application Penetration Test"
    parent = "Offensive Security"
    pageRef = "offensiveSecurity/webPenetrationTesting"
    weight = 20
  [[main]]
    name = "Malware Analysis and Reverse Engineering"
    parent = "Offensive Security"
    pageRef = "offensiveSecurity/malwareanalysis"
    weight = 40

  [[main]]
    name = "Capture The Flag"
    pageRef = "captureTheFlag"
    parent = "Offensive Security"
    weight = 50
    [[main]]
      name = "Huntress"
      parent = "Capture The Flag"
      pageRef = "/captureTheFlag/huntress"
      weight = 60
    [[main]]
      name = "Hack The Box"
      parent = "Capture The Flag"
      pageRef = "/captureTheFlag/hackthebox"
      weight = 70
    [[main]]
      name = "Try Hack Me"
      parent = "Capture The Flag"
      pageRef = "/captureTheFlag/tryhackme"
      weight = 80
    [[main]]
      name = "Proving Ground"
      parent = "Capture The Flag"
      pageRef = "/captureTheFlag/provingground"
      weight = 90

[[main]]
  name = "Machine Learning"
  pageRef = "machinelearning"
  weight = 95


[[main]]
  name = "Blockchain"
  pageRef = "blockchain"
  weight = 30


# Sub Navigaton


[[Subnavigation]]
  name = "Resources"
  pageRef = "resources"
  weight = 75

[[Subnavigation]]
  name = "Cheatsheets"
  pageRef = "cheatsheets"
  weight = 90









#[[main]]
#  name = "Test"
#  pageRef = "pagTest"
#  weight = 1000

#[[main]]
#  identifier = "twitter"
#  pre = "x-twitter"
#  url = "https://twitter.com/burufugu"
#  weight = 200

#[[main]]
#  identifier = "mastodon"
#  pre = "mastodon"
#  weight = 300
#  url = "https://masto.ai/@blowfish"

#[[main]]
#  identifier = "github"
#  pre = "github"
#  url = "https://github.com/r3sup3r"
#  weight = 1000


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Authors"
   pageRef = "authors"
   weight = 20
