# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "slate"   # values : blowfish (default), avocado, fire, ocean, forest, princess, neon, bloody, terminal, marvel, noir, autumn, congo, slate
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true  

replyByEmail = false

mainSections = ["docs"]
# robots = ""

disableImageOptimization = false
disableTextInHeader = false
# backgroundImageWidth = 1200

defaultBackgroundImage = "/img/kusanagi.jpg"
defaultFeaturedImage = "/img/featured.svg"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
  layout = "fixed" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background" # valid options: page, profile, hero, card, background, custom
  homepageImage = "/img/kusanagi.jpg" # used in: hero, and card
  showRecent = true  
  showRecentItems = 10
  showMoreLink = true
  showMoreLinkDest = "/content"
  cardView = true
  cardViewScreenWidth = true
  layoutBackgroundBlur = true # only used when layout equals background

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = true
  showAuthorBottom = false
  showHero = true
  heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  editURL = "https://github.com/nunocoracao/blowfish/tree/main/exampleSite/content"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = false
  relatedContentLimit = 6
  showTaxonomies = true 
  showAuthorsBadges = true 
  showWordCount = false
  sharingLinks = [ "linkedin", "github" ,"email", "twitter"]
  showZenMode = true

[list]
  showHero = true
  heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = true
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  showCards = true
  orderByWeight = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  cardView = false

[term]
  showHero = true
  heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  
[firebase]
  #apiKey = "AIzaSyB5tqlqDky77Vb4Tc4apiHV4hRZI18KGiY"
  #authDomain = "blowfish-21fff.firebaseapp.com"
  #projectId = "blowfish-21fff"
  #storageBucket = "blowfish-21fff.appspot.com"
  #messagingSenderId = "60108104191"
  #appId = "1:60108104191:web:039842ebe1370698b487ca"
  #measurementId = "G-PEDMYR1V0K"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[umamiAnalytics]
  # websiteid = "ABC12345"
  # domain = "llama.yoursite.com"
  # dataDomains = "yoursite.com,yoursite2.com"
  # scriptName = ""
  # enableTrackEvent = false

[selineAnalytics]
  # token = "XXXXXX"
  # enableTrackEvent = false

[buymeacoffee]
  identifier = "nunocoracao"
  globalWidget = true
  globalWidgetMessage = ""
  globalWidgetColor = "#FFDD00"
  globalWidgetPosition = "Right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

[rssnext]
  # feedId = ""
  # userId = ""
